buildersSpringConfig: mod/common/builders-declaration.xml
modPreGameSpringConfig: mod/common/application-context.xml
screenDeclarations:
  - screenName: selectShip
    interfaceConstructor: static:/mod/common/interface_shipselector.xml
    controller: spring:mod.common.selectshipcontroller
  - screenName: selectControl
    interfaceConstructor: spring:mod.common.selectcontrolgenerator
    controller: spring:mod.common.selectcontrolcontroller
  - screenName: selectKeys
    interfaceConstructor: spring:mod.common.selectkeysgenerator
    controller: spring:mod.common.selectkeyscontroller
  - screenName: selectRemoteControl
    interfaceConstructor: static:/mod/common/interface_remoteselector.xml
    controller: spring:mod.common.selectremotecontrolcontroller
  - screenName: objectCreationPhase
    interfaceConstructor: static:mod/common/empty_screen.xml
    controller: spring:mod.common.objectcreationphasecontroller
  - screenName: selectProfile
    interfaceConstructor: static:/mod/common/interface_profileselector.xml
    controller: spring:mod.common.profileselector
musicAmbients:
  - ambient: menu
    files:
      - /mod/common/music/AMemoryAway.ogg
      - /mod/common/music/Ocean Waves.ogg
