buildersSpringConfig: mod/common/builders-declaration.xml
modPreGameSpringConfig: mod/common/application-context.xml
screenDeclarations:
  - screenName: selectShip
    interfaceConstructor: mod.common.selectshipgenerator
    controller: mod.common.selectshipcontroller
  - screenName: selectControl
    interfaceConstructor: mod.common.selectcontrolgenerator
    controller: mod.common.selectcontrolcontroller
  - screenName: selectKeys
    interfaceConstructor: mod.common.selectkeysgenerator
    controller: mod.common.selectkeyscontroller

