buildersSpringConfig: mod/common/builders-declaration.xml
modPreGameSpringConfig: mod/common/application-context.xml
screenDeclarations:
  - screenName: selectShip
    interfaceConstructor: static:/mod/common/interface_shipselector.xml
    controller: spring:mod.common.selectshipcontroller
  - screenName: selectControl
    interfaceConstructor: spring:mod.common.selectcontrolgenerator
    controller: spring:mod.common.selectcontrolcontroller
  - screenName: selectKeys
    interfaceConstructor: spring:mod.common.selectkeysgenerator
    controller: spring:mod.common.selectkeyscontroller

