modName: Windtunnel (Development Mode)
modPreGameSpringConfig: mod/windtunnel/application-context.xml
modGameSpringConfig: mod/windtunnel/game-context.xml
buildersSpringConfig: mod/windtunnel/builders-declaration.xml
screenDeclarations:
  - screenName: windTunnelScreen
    interfaceConstructor: static:screen-snippets/gameplayLayout.xml
    controller: spring:mod.windtunnel.mainscreencontroller
moduleFlowRoot: root:root
moduleScreenFlow:
  - selectShip
  - selectControl
  - selectKeys
  - selectRemoteControl
  - windTunnelScreen