modName: CounterClock Game
modPreGameSpringConfig: mod/counterclock/application-context.xml
modGameSpringConfig: mod/counterclock/game-context.xml
buildersSpringConfig: mod/counterclock/builders-declaration.xml
screenDeclarations:
  - screenName: selectMap_counterclock
    interfaceConstructor: static:/mod/counterclock/interface_mapselector.xml
    controller: spring:mod.counterclock.mapselector
  - screenName: counterclockScreen
    interfaceConstructor: static:screen-snippets/gameplayLayout.xml
    controller: spring:mod.counterclock.mainscreencontroller
  - screenName: selectShip_counterclock
    interfaceConstructor: static:/mod/counterclock/interface_shipselector.xml
    controller: spring:mod.counterclock.selectshipcontroller
  - screenName: selectProfile_counterclock
    interfaceConstructor: static:/mod/counterclock/interface_profileselector.xml
    controller: spring:mod.counterclock.profileselector
  - screenName: selectControl_counterclock
    interfaceConstructor: spring:mod.counterclock.selectcontrolgenerator
    controller: spring:mod.counterclock.selectcontrolcontroller
  - screenName: selectKeys_counterclock
    interfaceConstructor: spring:mod.counterclock.selectkeysgenerator
    controller: spring:mod.counterclock.selectkeyscontroller
  - screenName: selectRemoteControl_counterclock
    interfaceConstructor: static:/mod/counterclock/interface_remoteselector.xml
    controller: spring:mod.counterclock.selectremotecontrolcontroller
moduleFlowRoot: root:root
moduleScreenFlow:
  - selectProfile_counterclock
  - selectShip_counterclock
  - selectMap_counterclock
  - objectCreationPhase
  - selectControl_counterclock
  - selectKeys_counterclock
  - selectRemoteControl
  - counterclockScreen