modName: CounterClock Game
modPreGameSpringConfig: mod/counterclock/application-context.xml
modGameSpringConfig: mod/counterclock/game-context.xml
buildersSpringConfig: mod/counterclock/builders-declaration.xml
screenDeclarations:
  - screenName: selectMap
    interfaceConstructor: static:/mod/counterclock/interface_mapselector.xml
    controller: spring:mod.counterclock.mapselector
  - screenName: selectProfile
    interfaceConstructor: static:/mod/counterclock/interface_profileselector.xml
    controller: spring:mod.counterclock.profileselector
  - screenName: counterclockScreen
    interfaceConstructor: static:screen-snippets/gameplayLayout.xml
    controller: spring:mod.counterclock.mainscreencontroller
moduleFlowRoot: root:root
moduleScreenFlow:
  - selectProfile
  - selectShip
  - selectMap
  - objectCreationPhase
  - selectControl
  - selectKeys
  - selectKeysDigital
  - selectRemoteControl
  - counterclockScreen